# Generated by Django 3.2.25 on 2024-12-01 22:43

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='BillingRecord',
            fields=[
                ('billing_id', models.IntegerField(db_column='Billing_ID', primary_key=True, serialize=False)),
                ('amount', models.DecimalField(blank=True, db_column='Amount', decimal_places=2, max_digits=10, null=True)),
                ('billing_date', models.DateField(blank=True, db_column='Billing_date', null=True)),
                ('payment_status', models.CharField(blank=True, db_column='Payment_status', max_length=10, null=True)),
            ],
            options={
                'db_table': 'Billing_Record',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='Customer',
            fields=[
                ('customer_id', models.IntegerField(db_column='Customer_ID', primary_key=True, serialize=False)),
                ('first_name', models.CharField(blank=True, db_column='First_name', max_length=10, null=True)),
                ('last_name', models.CharField(blank=True, db_column='Last_name', max_length=10, null=True)),
                ('street', models.CharField(blank=True, db_column='Street', max_length=30, null=True)),
                ('city', models.CharField(blank=True, db_column='City', max_length=20, null=True)),
                ('state', models.CharField(blank=True, db_column='State', max_length=20, null=True)),
                ('zip', models.CharField(blank=True, db_column='Zip', max_length=6, null=True)),
            ],
            options={
                'db_table': 'Customer',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='ParkingGate',
            fields=[
                ('gate_id', models.IntegerField(db_column='Gate_ID', primary_key=True, serialize=False)),
                ('is_operational', models.IntegerField(blank=True, db_column='Is_operational', null=True)),
            ],
            options={
                'db_table': 'Parking_Gate',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='ParkingLot',
            fields=[
                ('lot_id', models.IntegerField(db_column='Lot_ID', primary_key=True, serialize=False)),
                ('number_of_spots', models.IntegerField(blank=True, db_column='Number_of_spots', null=True)),
                ('street', models.CharField(blank=True, db_column='Street', max_length=30, null=True)),
                ('city', models.CharField(blank=True, db_column='City', max_length=20, null=True)),
                ('state', models.CharField(blank=True, db_column='State', max_length=20, null=True)),
                ('zip', models.CharField(blank=True, db_column='Zip', max_length=6, null=True)),
                ('available_spots', models.IntegerField(blank=True, db_column='Available_spots', null=True)),
            ],
            options={
                'db_table': 'Parking_Lot',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='ParkingRecord',
            fields=[
                ('record_id', models.IntegerField(db_column='Record_ID', primary_key=True, serialize=False)),
                ('time_entered', models.DateTimeField(blank=True, db_column='Time_entered', null=True)),
                ('time_left', models.DateTimeField(blank=True, db_column='Time_left', null=True)),
            ],
            options={
                'db_table': 'Parking_Record',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='ParkingZone',
            fields=[
                ('zone_id', models.IntegerField(db_column='Zone_ID', primary_key=True, serialize=False)),
                ('zone_name', models.CharField(blank=True, db_column='Zone_name', max_length=20, null=True)),
                ('zone_type', models.CharField(blank=True, db_column='Zone_type', max_length=15, null=True)),
                ('zone_capacity', models.IntegerField(blank=True, db_column='Zone_capacity', null=True)),
            ],
            options={
                'db_table': 'Parking_Zone',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='Spot',
            fields=[
                ('spot_id', models.IntegerField(db_column='Spot_ID', primary_key=True, serialize=False)),
                ('status', models.CharField(blank=True, db_column='Spot_status', max_length=10, null=True)),
            ],
            options={
                'db_table': 'Spot',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='Staff',
            fields=[
                ('staff_id', models.IntegerField(db_column='Staff_ID', primary_key=True, serialize=False)),
                ('name', models.CharField(blank=True, db_column='Name', max_length=20, null=True)),
                ('shift_start', models.TimeField(blank=True, db_column='Shift_start', null=True)),
                ('shift_end', models.TimeField(blank=True, db_column='Shift_end', null=True)),
            ],
            options={
                'db_table': 'Staff',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='Subscription',
            fields=[
                ('subscription_id', models.IntegerField(db_column='Subscription_ID', primary_key=True, serialize=False)),
                ('price', models.DecimalField(blank=True, db_column='Price', decimal_places=2, max_digits=10, null=True)),
                ('time_start', models.DateTimeField(blank=True, db_column='Time_start', null=True)),
                ('time_end', models.DateTimeField(blank=True, db_column='Time_end', null=True)),
            ],
            options={
                'db_table': 'Subscription',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='Vehicle',
            fields=[
                ('license_plate', models.CharField(db_column='License_plate', max_length=10, primary_key=True, serialize=False)),
                ('make', models.CharField(blank=True, db_column='Make', max_length=15, null=True)),
                ('model', models.CharField(blank=True, db_column='Model', max_length=15, null=True)),
                ('year', models.IntegerField(blank=True, db_column='Year', null=True)),
                ('type', models.CharField(blank=True, db_column='Type', max_length=5, null=True)),
                ('number_of_doors', models.IntegerField(blank=True, db_column='Number_of_doors', null=True)),
                ('fuel_type', models.CharField(blank=True, db_column='Fuel_type', max_length=10, null=True)),
                ('cargo_capacity', models.IntegerField(blank=True, db_column='Cargo_capacity', null=True)),
            ],
            options={
                'db_table': 'Vehicle',
                'managed': False,
            },
        ),
    ]
