runtime: python39
entrypoint: gunicorn -b :$PORT dbgroup3.wsgi

env_variables:
  DJANGO_SETTINGS_MODULE: "dbgroup3.settings"

handlers:
  - url: /static
    static_dir: static/

  - url: /.*
    script: auto
